### ISSUE TITLE
Simplify Setup

### ISSUE THREAD

**Issue by westonganger** [randy-girard/app_perf#1]
This application has a complicated setup process for the development environment with foreman and nginx and other non-standard things. I feel like this is will hinder adoption of this gem. As far as I can tell this is for your own custom setup. Can we clean this up so it it uses more conventional setup like most normal rails apps.

**Comment by randy-girard** [comment]
I would agree that it does have a lot of non-standard dependencies, that we can filter out and simplify. I would say however, once having those, the setup should be fairly simple, as its just a `bin/setup` and `bundle exec foreman start`.

We can easily remove nginx, and probably just run puma or thin easily enough. There may need to be some work to move to Sqlite3 for some of the querying that is used and functions for date related parts.

I will work/look into simplifying these things.

**Comment by westonganger** [comment]
Great to hear. Yeah it would really be good to be database agnostic for in my case I would prefer to use MySQL. Side question: Are you using this in production successfully currently?

**Comment by randy-girard** [comment]
I am not using it on any apps that I would consider production traffic. I have used it on apps that are "Production" as far as being deployed onto a server, but those sites are pretty much no traffic. I would definitely like to get some usage/overhead info and work on improving things for sure.

**Comment by randy-girard** [comment]
What do you think of this? @westonganger I had to update to support SQLite. It causes some issues with concurrency and what not, but this should get us rolling :)

**Comment by westonganger** [comment]
Yeah this is a decent start to get the ball rolling.
