### ISSUE TITLE
Allow dashboard panels to be dynamic

### ISSUE THREAD

**Issue by randy-girard** [randy-girard/app_perf#14]
Create a repository of dashboard panels that show different data and allow users to build their dashboards how they want.

- Allow panels to be resized (1, 2, 3, x columns?)
- Drag and droppable.
- Store to each user.
- Panels page to select from

**Comment by seanfcarroll** [comment]
Sounds awesome! So who's going to code it ;-)

**Comment by ferrisoxide** [comment]
Would there be any value in integrating with existing tools here (_e.g._ Grafana)?

**Comment by randy-girard** [comment]
Perhaps could provide some way to export data into grafana, but I don't want to rely on other tools. Trying to keep this project as self contained and with as few required dependencies as possible.

**Comment by randy-girard** [comment]
This isn't an issue. Going to close and start moving this kind of stuff into the projects section.
