### ISSUE TITLE
Trying to run on Mac OS El-Capitan, Puma return error

### ISSUE THREAD

**Issue by CaptEtienne** [randy-girard/app_perf#15]
Hello,

After dealing with quite a lot of little issues I finally get foreman to launch!

> 10:55:33 web.1    | started with pid 58528
> 10:55:33 worker.1 | started with pid 58529
> 10:55:35 worker.1 | I, [2017-08-17T10:55:35.564844 #58529]  INFO -- : Detecting runner...
> 10:55:35 worker.1 | I, [2017-08-17T10:55:35.565430 #58529]  INFO -- : Puma detected. You're valid
> 10:55:35 worker.1 | I, [2017-08-17T10:55:35.565463 #58529]  INFO -- : Initializing rack tracer.
> 10:55:35 worker.1 | I, [2017-08-17T10:55:35.565483 #58529]  INFO -- : Initializing rack middleware tracer.
> 10:55:35 web.1    | => Booting Puma
> 10:55:35 web.1    | => Rails 4.2.5.2 application starting in development on http://0.0.0.0:5000
> 10:55:35 web.1    | => Run `rails server -h` for more startup options
> 10:55:35 web.1    | => Ctrl-C to shutdown server
> 10:55:35 web.1    | I, [2017-08-17T10:55:35.918930 #58528]  INFO -- : Detecting runner...
> 10:55:35 web.1    | I, [2017-08-17T10:55:35.919692 #58528]  INFO -- : Puma detected. You're valid
> 10:55:35 web.1    | I, [2017-08-17T10:55:35.919731 #58528]  INFO -- : Initializing rack tracer.
> 10:55:35 web.1    | I, [2017-08-17T10:55:35.919750 #58528]  INFO -- : Initializing rack middleware tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.910437 #58528]  INFO -- : Detecting runner...
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.911272 #58528]  INFO -- : Puma detected. You're valid
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.912132 #58528]  INFO -- : Initializing actioncontroller tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.918572 #58528]  INFO -- : Initializing actionview tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.921291 #58528]  INFO -- : Initializing activerecord tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.921889 #58528]  INFO -- : Initializing activerecord-import tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.923540 #58528]  INFO -- : Initializing net-http tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.924038 #58528]  INFO -- : Initializing redis tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.925358 #58528]  INFO -- : Initializing sidekiq tracer.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.926687 #58528]  INFO -- : Starting worker.
> 10:55:36 web.1    | I, [2017-08-17T10:55:36.926770 #58528]  INFO -- : Worker is running.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.028715 #58529]  INFO -- : Detecting runner...
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.029213 #58529]  INFO -- : Puma detected. You're valid
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.029874 #58529]  INFO -- : Initializing actioncontroller tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.030655 #58529]  INFO -- : Initializing actionview tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.032426 #58529]  INFO -- : Initializing activerecord tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.032829 #58529]  INFO -- : Initializing activerecord-import tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.033956 #58529]  INFO -- : Initializing net-http tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.034417 #58529]  INFO -- : Initializing redis tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.035669 #58529]  INFO -- : Initializing sidekiq tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.040169 #58529]  INFO -- : Initializing sinatra tracer.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.040765 #58529]  INFO -- : Starting worker.
> 10:55:37 worker.1 | I, [2017-08-17T10:55:37.040866 #58529]  INFO -- : Worker is running.
> 10:55:37 web.1    | Puma 2.15.3 starting...
> 10:55:37 web.1    | * Min threads: 0, max threads: 16
> 10:55:37 web.1    | * Environment: development
> 10:55:37 web.1    | * Listening on tcp://0.0.0.0:5000
> 

but once I try to access localhost:5000 on my browser I get :

> 10:55:41 web.1    | 2017-08-17 10:55:41 +0200: Rack app error: #<NoMethodError: undefined method `type=' for nil:NilClass>
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/instruments/rack.rb:25:in `block in call'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/tracer.rb:43:in `start_trace'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/instruments/rack.rb:24:in `call'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
> 10:55:41 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

any idea ?

**Comment by CaptEtienne** [comment]
Trying to get a better understanding of the issue I checked the gem app_perf_rpm, in file tracer.rb I add line 44 :

`          result ||= Span.new
`

Now I get the login page but a redundant error appears in log :

> 11:35:46 web.1    | ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)):
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack_middleware.rb:49:in `call_with_tracing'
> 11:35:46 web.1    |   app_perf_rpm (0.0.2) lib/app_perf_rpm/instruments/rack.rb:22:in `call'
> 11:35:46 web.1    | 
> 11:35:46 web.1    | 
> 11:35:46 web.1    |   Rendered /Users/edejour/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.5ms)
> 11:35:46 web.1    |   Rendered /Users/edejour/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.5ms)
> 11:35:46 web.1    |   Rendered /Users/edejour/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
> 11:35:46 web.1    |   Rendered /Users/edejour/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (55.6ms)
> 11:35:46 web.1    | 2017-08-17 11:35:46 +0200: Rack app error: #<LocalJumpError: no block given (yield)>
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/instruments/rack.rb:25:in `block in call'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/tracer.rb:43:in `start_trace'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/app_perf_rpm-0.0.2/lib/app_perf_rpm/instruments/rack.rb:24:in `call'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
> 11:35:46 web.1    | /Users/edejour/.rvm/gems/ruby-2.3.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

Hope this help

**Comment by randy-girard** [comment]
To fix the DB connection issue, you can probably add a `pool: 30` to your `config/database.yml` file under the `development:` section. I'll have to look a bit more on the other error.

**Comment by randy-girard** [comment]
Just pushed an update for the gem that should fix it and added the pool to the config file. App is updated. Please close this if it resolves these issues.

**Comment by CaptEtienne** [comment]
Okay, I changed the pool option. If I can bring you any information, please ask.

**Comment by CaptEtienne** [comment]
The pull fixed this issue ! Thanks
