### ISSUE TITLE
authentication loop on /users/sign_in

### ISSUE THREAD

**Issue by CaptEtienne** [randy-girard/app_perf#16]
Hello again,
I had an issue on CSRF :

`Can't verify CSRF token authenticity`

So in application_controller I had the line :

`skip_before_action :verify_authenticity_token`

I can now log in as the log describe :

> 14:01:13 web.1    | Processing by Devise::SessionsController#create as HTML
> 14:01:13 web.1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ef3l/BOo61oCHzu6REn923ouuynH3m7mb42uW91UPSzSJvB8VBNbuDiM6h+1nZriIN4/Azlry09HsYRvci0iWA==", "user"=>{"email"=>"user@example.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Sign In"}
> 14:01:13 web.1    |   User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["email", "user@example.com"]]
> 14:01:13 web.1    |    (0.3ms)  BEGIN
> 14:01:13 web.1    |   SQL (0.5ms)  UPDATE "users" SET "last_sign_in_at" = $1, "current_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["last_sign_in_at", "2017-08-17 11:54:06.746905"], ["current_sign_in_at", "2017-08-17 12:01:13.214647"], ["sign_in_count", 3], ["updated_at", "2017-08-17 12:01:13.218107"], ["id", 1]]
> 14:01:13 web.1    |    (0.8ms)  COMMIT
> 14:01:13 web.1    | Redirected to http://localhost:5000/

but it seems I don't have the right to access Dashboard_controller :

`14:01:13 web.1    | Processing by DashboardController#show as HTML
14:01:13 web.1    | Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
`

Any idea ? does my skip_before_action broke it ? I'll keep searching on my side

Thanks ! Can't wait to test the product

**Comment by randy-girard** [comment]
You may have to clear your sessions if you pulled a new version and reran the bin setup step

**Comment by CaptEtienne** [comment]
I tried everything, compared to my other projects on rails 4 with device. 
But I can't make it work.

what I tried :

- `bundle update`
- `:devise, 3.5.3` (known to work on another project)
- `= csrf_meta_tags` on the layout public.html.erb
- `rake tmp:clear`
- `skip_before_action :verify_authenticity_token` (with and without)
- `config.action_dispatch.default_headers = {'X-Frame-Options' => 'ALLOWALL'}` in development.rb
- SQLite and Postgresql
- 2 different computer

... I'm out of ideas

**Comment by randy-girard** [comment]
There isnt anything on that dashboard that authorizes. Ive had similar issues happen due to a session stored from a previous login after i reseed the db. Did you try fully clearing out the session from browser?

**Comment by CaptEtienne** [comment]
Yes, I also tried from a different one : Safari / Chrome

**Comment by CaptEtienne** [comment]
I commented `gem "app_perf_rpm", "0.0.3"`

I can now log without issue

**Comment by randy-girard** [comment]
Hmm, thats strange.

**Comment by CaptEtienne** [comment]
Indeed ! Do you alter the request ?

**Comment by randy-girard** [comment]
It shouldn't be getting altered, although I guess there is the possibility. I've never run into this issue

**Comment by CaptEtienne** [comment]
a "detail" that may lead to explanation : fonts and all the .map files were 404

now they're back (when I comment the gem)

**Comment by randy-girard** [comment]
Did you change any of the configuration at all after pulling the project down? Trying to replicate it locally.

**Comment by CaptEtienne** [comment]
I didn't change anything, also I had to install a redis-server

**Comment by randy-girard** [comment]
OK, the rpm must be doing something because with it, I can't use the "Sign Out" link either. I'll look into this more.

**Comment by CaptEtienne** [comment]
I tricked the system : by loging IN  without gem I could restart the server with the gem and keep my session : I'm now logged

just a temporary band-aid.

**Comment by randy-girard** [comment]
Ok. I have an idea where it is but prob wont be able to address it until later this evening.

**Comment by randy-girard** [comment]
So I tracked it down to the rack-middleware instrumentation. Investigating why still...

**Comment by CaptEtienne** [comment]
Let me know if I can bring any help about this!

**Comment by randy-girard** [comment]
Just pushed up an update that removes the rack-middleware instrumentation while I can figure out what the deal with it is.

**Comment by randy-girard** [comment]
It will still instrument rack as a whole, just not the individual rack middleware....

**Comment by randy-girard** [comment]
OK I have a fix for it to get back in. just have to do some more testing.

**Comment by CaptEtienne** [comment]
I just tested the new version and the login is working fine ! Great job!

**Comment by CaptEtienne** [comment]
Should I close or you need to test more?

**Comment by randy-girard** [comment]
Lets keep it open until i fully fix the issue

**Comment by randy-girard** [comment]
OK Just pushed updates that should fix all this. I'm going to close it.
