### ISSUE TITLE
Ruby only?

### ISSUE THREAD

**Issue by MACscr** [randy-girard/app_perf#17]
Is it only meant to be an APM for Ruby or are you planning on supporting other languages like php?

**Comment by randy-girard** [comment]
Any language is support as long as you can post the data in right format. Eventually I had planned to add more but ruby is the focus right now.

**Comment by MACscr** [comment]
Unless I am blind, the only POST example i see is for authenticating with the api and not the actual fields/value formats that can be posted.

**Comment by randy-girard** [comment]
You POST to the agent_listener. You "authenticate" at the same time using a key, along with the data.

**Comment by MACscr** [comment]
Ah, so the ruby agent would be installed on the system i want tracked and then i could actually post data to it, which would then send data to the apm host server?

**Comment by randy-girard** [comment]
There are three pieces:

1. This app (app_perf). This is the application that collects the data from a POST to agent_listener.
2. The ruby APM (app_perf_rpm). This is for ruby/rails apps and collects application metrics and posts to the agent_listener automatically.
3. The system agent (app_perf_agent). This monitors the metrics of a server and posts those automatically to agent_listener.

Anything outside of these cases, such as another language, would have to be written to post to agent listener.

Hope thats clear.

**Comment by MACscr** [comment]
But what is the url for the agent_listener and how do we know what POST fields/value types it supports? Is this documented anywhere? As mentioned previously, it seems only the authentication is documented.

**Comment by randy-girard** [comment]
The information I have currently is listed under https://github.com/randy-girard/app_perf/blob/master/README.md#how-the-data-model-works

As noted there, I don't have data examples yet of what to submit, but if you look at the rpm or agent, you can see how the data is built up and added.
