### ISSUE TITLE
docker-compose? 

### ISSUE THREAD

**Issue by Daniel-ltw** [randy-girard/app_perf#20]
You can enable users to spin the whole stack up easily with docker-compose. 

With users being able to stack this up quickly, the adoption of this would be quicker. 

Just my 10c to enhance this project.

**Comment by randy-girard** [comment]
Thanks for the feedback. I will definitely look into adding this as soon as I can.

**Comment by randy-girard** [comment]
Just worked on adding docker compose. Should be good now.

https://github.com/randy-girard/app_perf#setup-docker
