### ISSUE TITLE
Official Docker Hub

### ISSUE THREAD

**Issue by krainboltgreene** [randy-girard/app_perf#25]
Hello! I'm trying to use app_perf just like I use sentry, as a docker image that I add to my compose stack. However, there doesn't seem to be an official docker hub image and the one I've tried has difficulties.

I would love to help set this up as it would directly benefit me.

Here are the things I've identified:

  0. The dockerfile doesn't seem to be designed with production in mind
  0. The dockerfile runs migrations, but as sentry this should probably manually be done by the user
  0. The dockerfile runs multiple processes, but this should ultimately be handled by the upper level service (my docker-compose.yml, for example, like sentry)
  0. The database url isnt' designed for upper level service control. For example, sentry only needs a linked postgres, redis, & memchaced OR a SENTRY_(MEMCACHED|POSTGRES|REDIS)_(HOST|USER|PASSWORD) environment variable.

**Comment by randy-girard** [comment]
The "official" dockerhub for the project is https://hub.docker.com/r/rgirard59/app-perf/, however I haven't updated it in some time. I would very much appreciate any help you would like to give in helping work with me on this as well.

Feel free to join the slack chat (link in the readme) or the facebook group and we can chat more off "issue" topic about it if you would like.
