### ISSUE TITLE
PG::UntranslatableCharacter: ERROR: unsupported Unicode escape sequence

### ISSUE THREAD

**Issue by EvTi** [randy-girard/app_perf#26]
99% of tasks in sidekiq completed with an error and the data is not displayed.

`PG::UntranslatableCharacter: ERROR: unsupported Unicode escape sequence LINE 1: ...41534423828,11.723041534423828,'1ee4b11671ac41f1','{"compone... ^ DETAIL: \u0000 cannot be converted to text. CONTEXT: JSON`

**Comment by randy-girard** [comment]
Can you provide sample application that has this issue?

**Comment by randy-girard** [comment]
Please reopen and provide an app that I can test with in GitHub somewhere, if this is still an issue.
