### ISSUE TITLE
Mysql?

### ISSUE THREAD

**Issue by aantix** [randy-girard/app_perf#27]
Is there any technical reason why MySQL can not be used?

**Comment by randy-girard** [comment]
While technically there is no reason, the project is currently using some features that I think may only available in Postgres out of the box. I also have some plans to use some things down the road that are Postgresql specific extensions.

There could be some code added to check which adapter is being used and change accordingly, but its not something on my immediate plans. You are welcome to take a stab at it and submit a PR though.
