### ISSUE TITLE
App Perf Agent crashes on launch on macOS Mojave with Vmstat issue

### ISSUE THREAD

**Issue by eclair4151** [randy-girard/app_perf#28]
11:52:56 agent.1  | I, [2019-02-06T11:52:56.494624 #26388]  INFO -- : Loading Load monitoring.
11:52:56 agent.1  | I, [2019-02-06T11:52:56.495032 #26388]  INFO -- : Loading Network monitoring.
11:52:56 agent.1  | I, [2019-02-06T11:52:56.495453 #26388]  INFO -- : Loading CPU monitoring.
11:52:56 agent.1  | I, [2019-02-06T11:52:56.495807 #26388]  INFO -- : Loading Memory monitoring.
11:52:56 agent.1  | I, [2019-02-06T11:52:56.496203 #26388]  INFO -- : Loading Disk monitoring.
11:52:56 agent.1  | I, [2019-02-06T11:52:56.496568 #26388]  INFO -- : Starting AppPerfAgent.
11:52:56 agent.1  | bundler: failed to load command: app_perf_agent (/usr/local/bin/app_perf_agent)
*11:52:56 agent.1  | NoMethodError: undefined method `network_interfaces' for Vmstat:Module*
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/vmstat-2.3.0/lib/vmstat/snapshot.rb:29:in `initialize'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/vmstat-2.3.0/lib/vmstat.rb:83:in `new'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/vmstat-2.3.0/lib/vmstat.rb:83:in `snapshot'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/plugin/system/cpu.rb:11:in `initialize'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/plugin.rb:20:in `new'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/plugin.rb:20:in `map'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/plugin.rb:20:in `plugins'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/worker.rb:35:in `collect'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/worker.rb:23:in `start'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/lib/app_perf_agent/cli.rb:27:in `run'
11:52:56 agent.1  |   /Library/Ruby/Gems/2.3.0/gems/app_perf_agent-0.0.6/exe/app_perf_agent:7:in `<top (required)>'
11:52:56 agent.1  |   /usr/local/bin/app_perf_agent:22:in `load'
11:52:56 agent.1  |   /usr/local/bin/app_perf_agent:22:in `<top (required)>'
11:52:56 agent.1  | exited with code 1
11:52:56 system   | sending SIGTERM to all processes
11:52:56 worker.1 | 2019-02-06T16:52:56.512Z 26331 TID-ov6yrd9yc DEBUG: Got TERM signal
11:52:56 web.1    | Stopping web server... done
11:52:56 web.1    |
11:52:56 worker.1 | 2019-02-06T16:52:56.512Z 26331 TID-ov6yrd9yc INFO: Shutting down
11:52:56 web.1    |
11:52:56 worker.1 | 2019-02-06T16:52:56.512Z 26331 TID-ov6yrd9yc INFO: Terminating quiet workers

**Comment by eclair4151** [comment]
This is an issue with the Vmstat ruby library

**Comment by eclair4151** [comment]
fixed here: https://github.com/threez/ruby-vmstat/issues/23

**Comment by randy-girard** [comment]
Fixed with https://github.com/randy-girard/app_perf/commit/5f07e2ca2cf9fd726aab27dc1f5e396f7c644d5e
