### ISSUE TITLE
Notes about setup

### ISSUE THREAD

**Issue by fernandoluizao** [randy-girard/app_perf#30]
Hi,

Trying to setup your project, I encontered some problems:
```
./bin/setup
```
Fails because there are no JS runtimes on Gemfile:
```
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes
```
I added `therubyracer`, and setup now works. Inspecting the Gemfile, `execjs` was pulled by `bootstrap-sass`and `uglifyer`. Wouldn't be better to use webpacker for this?

The second problem was related to webpacker. I didn't have node stuff installed, and I'm not a frontend guy, and since the readme doesn't mentions about this, I struggled for some time, until everything worked. Steps I took:

1. Install node (via [nvm](https://github.com/creationix/nvm))
2. Install [yarn](https://yarnpkg.com/en/docs/install)
3. rails webpacker:install

Something like this shouldn't be on the readme? Not sure if I did correctly because I don't have experience with webpacker, but the app seems to be running fine :smile: 

Thanks for your project, I'm very interested in helping. Do you have some kind of roadmap?

**Comment by randy-girard** [comment]
I just recently updated to Rails 5.2 using webpacker, so I probably just forgot to update the README. I will work on getting that and `bin/setup` up to date to make this easier.

I don't have anything specific for a roadmap at this point, just a bunch of random things in my head. I think the first major think I want to tackle is cleaning up the RPM gem and sending up some consolidated stats around things like requests so I can so total requests in the app. I am open to discussions though.

**Comment by randy-girard** [comment]
I added some instructions about node/postgres/yarn install. I'm not sure about the webpacker yet, as that is already installed in the app and shouldn't be a problem.
