### ISSUE TITLE
JSON::GeneratorError: Invalid Unicode

### ISSUE THREAD

**Issue by libreayudmonte** [randy-girard/app_perf#35]
App_perf has a problem decoding data it receives from the application:

20:34:14 worker.1 | 2019-05-09T18:34:14.583Z 16521 TID-greqelkyx WARN: JSON::GeneratorError: Invalid Unicode [9c 8d 56 e1 6e] at 203 in 'SETEX kuko_limelight_cache:views/admin/task_instances/81115-20190502132338243064/tasks/176-20181001121933503019/task_states/970-20181001121933532399 1728000 o: ActiveSupport::Cache::Entry
20:34:14 worker.1 | :
                     @value"vx��V�n�6��(�
                                               T?
20:34:14 worker.1 | U�� …  <more data>'
20:34:14 worker.1 | 2019-05-09T18:34:14.583Z 16521 TID-greqelkyx WARN: /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/json/encoding.rb:22:in `encode'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/json/encoding.rb:22:in `encode'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activerecord-5.2.2.1/lib/active_record/type/json.rb:18:in `serialize'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activemodel-5.2.2.1/lib/active_model/type/helpers/mutable.rb:8:in `cast'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:175:in `type_cast'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:42:in `value'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activemodel-5.2.2.1/lib/active_model/attribute_set.rb:48:in `fetch_value'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/read.rb:40:in `__temp__071697c6f61646'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:178:in `block in get_database_types'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:178:in `select'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:178:in `get_database_types'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:193:in `build_database_calls'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:77:in `process_data'
20:34:14 worker.1 | /home/app_perf/app_perf/app/workers/open_tracing_worker.rb:37:in `perform'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/execution.rb:39:in `block in perform_now'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/execution.rb:24:in `block in execute'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:83:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/execution.rb:22:in `execute'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activejob-5.2.2.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/app_perf_rpm-0.2.4/lib/app_perf_rpm/instruments/sidekiq.rb:24:in `call'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
20:34:14 worker.1 | /usr/local/rvm/gems/ruby-2.6.3@app_perf/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'

**Comment by randy-girard** [comment]
Can you provide a sample application that causes this issue. Clearly looks like some type of UTF issue but I cannot reproduce. Thanks

**Comment by randy-girard** [comment]
Please reopen and provide an app that I can test with in GitHub somewhere, if this is still an issue.
