### ISSUE TITLE
Not pickup .env 

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#36]
1. I put my .env at root with following lines

POSTGRES_USERNAME="foo"
POSTGRES_PASSWORD="bar"
POSTGRES_HOSTNAME=""

Then error
PG::ConnectionBad: fe_sendauth: no password supplied

Question 2
Can we use in Intranet with SQL Server

Thanks
P Kul

**Comment by kul1** [comment]
It's worked perfect.
It's worked across different servers
It's worked from Docker(App_Perf) and Application different servers

What I can not make it work yet are:
1. app_perf_agent in Windows 10
2. app_perf_rpm with SQL Server adapter

**Comment by randy-girard** [comment]
Windows 10 and SQL server aren't support as of yet with this app. What are the issues you are having with #3?
