### ISSUE TITLE
undefined method `boot_time' for Vmstat:Module (NoMethodError) in Windows 10

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#40]
I, [2019-06-18T14:52:54.485883 #25108]  INFO -- : Initializing with options: {:license_key=>"30b5805c-25d8-4fcd-875e-4fd9be32993e", :host=>"10.0.75.1:5000"}
I, [2019-06-18T14:52:54.499884 #25108]  INFO -- : Loading CPU monitoring.
I, [2019-06-18T14:52:54.502884 #25108]  INFO -- : Loading Disk monitoring.
I, [2019-06-18T14:52:54.505885 #25108]  INFO -- : Loading Load monitoring.
I, [2019-06-18T14:52:54.509885 #25108]  INFO -- : Loading Memory monitoring.
I, [2019-06-18T14:52:54.513891 #25108]  INFO -- : Loading Network monitoring.
I, [2019-06-18T14:52:54.514885 #25108]  INFO -- : Starting AppPerfAgent.
C:/Ruby223/lib/ruby/gems/2.2.0/gems/vmstat-2.3.1/lib/vmstat/snapshot.rb:24:in `initialize': undefined method `boot_time' for Vmstat:Module (NoMethodError)
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/vmstat-2.3.1/lib/vmstat.rb:83:in `new'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/vmstat-2.3.1/lib/vmstat.rb:83:in `snapshot'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin/system/cpu.rb:11:in `initialize'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `new'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `map'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/plugin.rb:20:in `plugins'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/worker.rb:35:in `collect'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/worker.rb:23:in `start'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/lib/app_perf_agent/cli.rb:27:in `run'
        from C:/Ruby223/lib/ruby/gems/2.2.0/gems/app_perf_agent-0.0.7/exe/app_perf_agent:7:in `<top (required)>'
        from C:/Ruby223/bin/app_perf_agent:23:in `load'
        from C:/Ruby223/bin/app_perf_agent:23:in `<main>'

> 
> Window 10
> Ruby 2.2.3
> 
>

**Comment by randy-girard** [comment]
Can you try installing this gem locally and just creating a small script that runs it to see if it works on Windows with the newer versions? I know that Windows wasn't on the list of supported OSes. I may have to check and not run on windows for the time being.

https://github.com/threez/ruby-vmstat

**Comment by kul1** [comment]
ok,

**Comment by randy-girard** [comment]
Closing this. This is an issue in the agent, not the main app. Please reopen there if you still need assistance.
