### ISSUE TITLE
host Shown unknown data

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#42]
In Hardware Menu
It's always shown same 2 lines in diifferent servers Application s
![hosts](https://user-images.githubusercontent.com/3953832/60181854-1fec4080-97f1-11e9-825b-9b5a8672d4a6.PNG)

1. Why 2 data in one host
2. Why each host has same 2 lines of data.
Remark:
In app_perf_agent license number it was given different number than app_perf_rpm or app_perf license number.

**Comment by randy-girard** [comment]
Are you running the agent when you start up the app and the agent seperately. How are you running the app and what is the procfile look like. Are you using docker or any containerization?

**Comment by kul1** [comment]
I ran agent in seperated tmux windows in order to let in run both while logged out.
The app_perf still in Docker in VM Centos share port 5000, while agent and my Application both ran in seperated VM Servers
Now after doing that I have 3 lines with 2 unknown data and 1 is the expected agent server

**Comment by randy-girard** [comment]
Every agent that is running will likely report its own data.

**Comment by kul1** [comment]
Thanks, perhap I still have some agent ran in others test and send to same server:5000.
