### ISSUE TITLE
Not collect all data or just sampling ?

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#44]
Not sure this should be problem/bug or just feature that collect only sample.
I would be nice to trace all events all time. If so what we test run compare same application on different setup it 's not seem to collect all click.
It just happened when we tried to compare performance of our different version of own Application as shown.

The first one not collect some click in menu as compare with the second one.

<img width="563" alt="App1 access" src="https://user-images.githubusercontent.com/3953832/60372030-36e58b00-99c9-11e9-9b28-12046a972f66.PNG">

This is the second App click at the same time, seem to collect most of the click.

<img width="561" alt="App2 access" src="https://user-images.githubusercontent.com/3953832/60372035-3a791200-99c9-11e9-9df7-283d4c8e8c86.PNG">

**Comment by randy-girard** [comment]
There is a sample default of about 10% I believe. You can change this in your RPM configuration. https://github.com/randy-girard/app_perf_rpm/blob/master/lib/app_perf_rpm/configuration.rb#L31

**Comment by kul1** [comment]
Thanks, It seem to collect more data. 
1. However to see the result, it took a few hours. It not shown immediately. Is that about the APP_PERF_FLUSH_INTERVAL
2. The Hard Disk was enormous used
3. CPU gone to 98% at some point
4. Before I set to have more sampling rate, I found the app_perf database had gone to 1.4 Gig in past 1 month of few test ( test click 1 min a day)
5. Also found some data not from our expected Application rails in the trace in App_Perf (very weird php data from somewhere, perhaps other department ! since this is in our firewall server of this corp, that might cause huge amount of data)


This Centos VM running 
1 App_Perf in Docker
2. Two of our own Application using app_perf_rpm (withour app_perf_agent) (I test clicks until for a min the slow responsed) (already set to 100 samling rate )
Also receiving from other servers below:
3. Receiving 3 others Application from Other 2 servers 
Here is the CPU info using cat /proc/cpuinfo

```

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell)
stepping        : 2
microcode       : 0x1
cpu MHz         : 2593.752
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
bogomips        : 5187.50
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel Core Processor (Broadwell)
stepping        : 2
microcode       : 0x1
cpu MHz         : 2593.752
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
bogomips        : 5187.50
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

**Comment by kul1** [comment]
I think this caused by data still in Redis/Sidekiq. Lots of data still pending, about 50% Failed might because I did change application/servers/license without aware of this cache. 
![sidekiq1](https://user-images.githubusercontent.com/3953832/61048582-3af1af80-a3b0-11e9-8abb-ff98d680646a.PNG)
![sidekiq2](https://user-images.githubusercontent.com/3953832/61048583-3af1af80-a3b0-11e9-8a97-f375dde3a40f.PNG)

**Comment by randy-girard** [comment]
Just delete the queues if its not important or relevant any longer. The data can be removed and it will just start to create more.
