### ISSUE TITLE
Can not delete applications or Add user

### ISSUE THREAD

**Issue by kul1** [randy-girard/app_perf#45]
Don't know these functions not implemented or need to config anything, I tried install several times it shown the same errors.

<img width="600" alt="App_perf_delete_error" src="https://user-images.githubusercontent.com/3953832/61151461-fc451d80-a4b3-11e9-91cd-3796272030af.PNG">
<img width="584" alt="App_perf-add-user" src="https://user-images.githubusercontent.com/3953832/61151476-0830df80-a4b4-11e9-9da8-19c403e7145e.PNG">

**Comment by randy-girard** [comment]
In order to add a user, you need to have a mail server running. You can use `mailcatcher`.  Also pushed an update that should fix the delete issue.
