### ISSUE TITLE
:187:in `render_template'

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [randy-girard/app_perf#46]
Hi i was getting error 
lib/app_perf_rpm/instruments/action_view.rb:187:in `render_template'
ArgumentError (wrong number of arguments (given 4, expected 1..3)):

**Comment by Laykou** [comment]
👍 I think that's the issue with Rails 6

**Comment by randy-girard** [comment]
I just push an update to the apm to handle Rails 6.
