### ISSUE TITLE
How to enable error catching?

### ISSUE THREAD

**Issue by knx** [randy-girard/app_perf#47]
Is there anything special to be done to enable error catching from connected apps?

**Comment by randy-girard** [comment]
You shouldn't need to do anything special as long as its a Rails app. Just add the gem to the project and it should start picking up the errors. Can you provide more details if you are having an issue?

**Comment by knx** [comment]
Actually I don't have the issue. The errors started to appear. Sorry for the confusion. 

Are you open for contributions? I'd like to add:

1) request env reporting along with the database trace
2) possibility to close, merge and ignore errors
3) Missing specs
