### ISSUE TITLE
Overhead?

### ISSUE THREAD

**Issue by vitobotta** [randy-girard/app_perf#49]
Hi! I am playing with this app right now. I am looking to self host something like this because I can't use a traffic-based paid product or I will go bankrupt :D  

I got it working with Docker and I was wondering how much is the overhead of tracing on top of requests etc? Is it lightweight enough or can it impact on the performance of my application somehow? How are traces captured?

I was also thinking to add a Helm chart for deployment to Kubernetes, since that's how I would use it. Would it be OK if I send a pull request if I do this?

Thanks in advance for any clarification :)

**Comment by vitobotta** [comment]
In particular, with the data from the app itself I am seeing that there is a delay before e.g. ActionController stuff starts to be processed:

<img width="2372" alt="Screenshot 2020-02-03 at 17 12 19" src="https://user-images.githubusercontent.com/283811/73664665-73d4d700-46a8-11ea-83da-3bcdb18a8d67.png">

**Comment by randy-girard** [comment]
Hey, thanks for checking out the app. The overhead shouldn't be too bad if you have a low traffic site. I haven't profiled the app itself yet against a high traffic site, so I am not sure what the impact of that would be. I do notice that the "delay" you are noticing typically happens when running in development. Is that the case? I would also be interested in knowing if you are running any other rack apps.

Also, yes, you can open pull requests to add functionality for sure :)

**Comment by vitobotta** [comment]
Yep I'm just testing with the app's own data in development mode. I'll see if I can try some load test or something. I am working on something that could end up with quite a bit of traffic, so that's what worries me. BTW it doesn't seem to track Sidekiq/ActiveJob, right?

**Comment by randy-girard** [comment]
It should be tracking sidekiq. It's possible there is a version issue. What version are you using? There are currently no activejob hooks though.

**Comment by vitobotta** [comment]
I am using master (I don't see other branches or tags?). What I meant is that I don't see tracing for jobs. I think it tracks when a job is enqueued in web requests, but does it also trace the job itself? I don't see this, perhaps I'm blind 😃 

If I allocate 10GB for Postgres, how much data do you think it can store? It would be nice if it was possible to configure data retention. Or is it already? Thanks!

**Comment by vitobotta** [comment]
How can I test the error tracking? I tried introducing a syntax error in the users controller but I still see "No errors!"

**Comment by randy-girard** [comment]
It might be possible its not getting submitted or tracked properly. I recently updated a lot of stuff, and possible I broke something. I'll try to take a look as soon as I can with that.

**Comment by vitobotta** [comment]
Cool, thanks. BTW I enabled class caching just to see how it's in production mode, and the delay between the start of the rack thing and the start of the ActionController thing is much shorter 😄

**Comment by vitobotta** [comment]
Does it track a % of the requests? Some sort of sampling?

**Comment by randy-girard** [comment]
You can track all requests if you set the proper setting int he RPM. I think by default its like 10% of requests. It still need to report high level info though regardless of sample rate. The data is all trace based at this time.

**Comment by vitobotta** [comment]
Gotcha. Since this app requires Postgres and I was also thinking of switching my app from MySQL to Postgres, I am now testing a Postgres operator for Kubernetes, then I'll look into the Helm chart for the APM. Does the APM work only with applications that use Postgres or also MySQL? Thanks

**Comment by randy-girard** [comment]
The APM should support MYSQL. So you can use it with apps that use mysql. The main AppPerf app does not however, since I believe its using some specific postgresql things.

**Comment by vitobotta** [comment]
@randy-girard Oh that's cool. I was thinking to switch anyway because I like the point in time recovery with Postgres so I am learning about Postgres right now.  How much data does the APM store? Is there a data retention somehow? I was thinking to give a 10GB volume to it. Does it just keep adding data or does it automatically clean up older data? Thanks!

**Comment by randy-girard** [comment]
There used to be a built in feature for retention, but it was removed. Its on the user to decide, at this time, how/if/when they want to expire data at the moment. I'll probably create a task that will make this easier. It depends on the sample rate/frequency/amount of traffic, so hard to tell how much data it would add.

**Comment by vitobotta** [comment]
What would be the easiest way to expire old data at the moment?

**Comment by randy-girard** [comment]
Probably just a delete statement of the various tables (traces, spans, metrics, etc) where timestamp is older than X.

**Comment by vitobotta** [comment]
Gotcha. Thanks :)

**Comment by vitobotta** [comment]
Hi @randy-girard I added the Helm chart (will send the PR when I am done testing) and have successfully deployed to Kubernetes with it. However I am having a couple of issues:

- the code snippet that I am supposed to add to an initializer in my app doesn't show how to set the URL of the APM app. How do I do this? I tried setting the APP_PERF_HOST variable to the URL of my instance of the APM but nothing happens. I don't see any requests in the logs of the APM when I navigate pages in my app.
- It seems that there is a problem with loading jQuery somehow. Is it because of some work in progress? I build the image from master because there are no other branches apart from an outdated one.

Thanks!

**Comment by vitobotta** [comment]
Nevermind about jQuery, I had to precompile the assets in production mode. Why is the app not using Puma or something better than Webrick?

**Comment by vitobotta** [comment]
I think it's receiving requests from the app now but I see ""POST /api/listener/3/ HTTP/1.1" 404 0" in the logs

**Comment by vitobotta** [comment]
Got it working, I had misspelled one variable. I can see now data in the APM, but from looking at the logs it looks like the gem is sending a massive amount of stuff inserted in the backtraces table. It includes tons of source code. What's happening? Also the OpenTracingWorker job is enqueued with a huge encode argument. No idea of what it is. Thanks in advance for any clarification.

**Comment by vitobotta** [comment]
From looking at the gem code I have added this to the configuration snippet:

```ruby
    rpm.instrumentation = {
      :rack                    => { :enabled => true, :backtrace => :app, :source => false, :trace_middleware => false },
      :roda                    => { :enabled => true, :backtrace => :app, :source => false },
      :grape                   => { :enabled => true, :backtrace => :app, :source => false },
      :active_record           => { :enabled => true, :backtrace => :app, :source => false },
      :active_record_import    => { :enabled => true, :backtrace => :app, :source => false },
      :active_model_serializer => { :enabled => true, :backtrace => :app, :source => false },
      :action_view             => { :enabled => true, :backtrace => :app, :source => false },
      :action_controller       => { :enabled => true, :backtrace => :app, :source => false },
      :emque_consuming         => { :enabled => true, :backtrace => :app, :source => false },
      :redis                   => { :enabled => true, :backtrace => :app, :source => false },
      :sequel                  => { :enabled => true, :backtrace => :app, :source => false },
      :sidekiq                 => { :enabled => true, :backtrace => :app, :source => false },
      :sinatra                 => { :enabled => true, :backtrace => :app, :source => false },
      :net_http                => { :enabled => true, :backtrace => :app, :source => false },
      :typhoeus                => { :enabled => true, :backtrace => :app, :source => false },
      :faraday                 => { :enabled => true, :backtrace => :app, :source => false }
    }
```

So I tried both setting source to false and backtrace to nil, but nothing changes. A TON of code is sent and inserted into the backtraces table.

**Comment by vitobotta** [comment]
Uhm... I have a doubt: if backtrace is set to :app is it supposed to only include the backtraces for files in the app directory? When I create the Docker image for my app I vendor/cache all the gems in <app path>/vendor/cache. Could that be the reason why the backtraces are so big?

**Comment by vitobotta** [comment]
Looks like I might have to give up unless there is a way to optimise this... Pages for my app render in around 20ms in production mode without the app_perf gem. With the gem, they render 10x slower, at around 200ms. I don't know whether it's because of the enormous backtrace or something else. Hopefully you can give me some hints on how to improve this. Sorry for the many comments! 😄

**Comment by randy-girard** [comment]
1. The app should be using passenger. This is due to a concurrency related thing, if I recall correctly. You can switch to puma if you would like, but at this time, its just using passenger.
2. The encoded data is the payload compressed for transit, to save space in redis. Something I think I need to rethink.
3. `source` set to false or nil should work. If its not, there is an issue there.
4. You can limit the amount of sampling by setting the sample rate `https://github.com/randy-girard/app_perf_rpm/blob/master/lib/app_perf_rpm/configuration.rb#L31` lower. Not sure what you are at.

There is definitely room to optimize this app, I just haven't had as much time as I would like to, unfortunately. I make no claims that this is anywhere near production ready.

**Comment by vitobotta** [comment]
H @randy-girard, I totally understand :) I was hoping I could use this now already because it would be very expensive for me to use a traffic-based paid service. I am very happy to have found this app. I will try it again a little later because of the increased response, and if I find the time I'll see if I can contribute somehow. I have created the PR ( #50 ) for the Helm chart. I'll close this for now. Thanks!
