### ISSUE TITLE
Proper Steps

### ISSUE THREAD

**Issue by TT9gth** [randy-girard/app_perf#54]
Hi,

Can you update this site with proper steps that need to be followed in order to use App_Perf apm, or just a small video will also help?

OS: Windows 10

**Comment by randy-girard** [comment]
Is there something specific you are running into? Most of the information you would need is either in the readme for the project, or on the application page within the app when you create a new application.

Also, I should note, that I have no tested with application on any windows machines, and am not sure of the support there. I would recommended using something like virtualBox or docker in that case.

**Comment by TT9gth** [comment]
> Is there something specific you are running into? Most of the information you would need is either in the readme for the project, or on the application page within the app when you create a new application.
> 
> Also, I should note, that I have no tested with application on any windows machines, and am not sure of the support there. I would recommended using something like virtualBox or docker in that case.

**Comment by TT9gth** [comment]
Hi,

I look forward to using this App_Perf tool for the monitoring, when I tried implementing on Windows, I faced below given errors.
I set up all the required Prerequisites in my system, in ruby I'm not able to run below-given command.
./bin/setup
So I tried installing each individually (system "yarn install"  & system "gem install bundler).

The next step is to run the below command.
bundle exec foreman start
I'm getting below error after executing the above command.
"https://github.com/productboard/postgres_ext.git (at rails-6@42d908a) is not yet checked out. Run `bundle install` first."

and when I'm trying to run "bundle install" command, again getting the below error.

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Error: "First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22https+%2F%2Fgithub.com%2Fproductboard%2Fpostgres_ext.git%22+%22C+%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fcache%2Fbundler%2Fgit%2Fpostgres_ext-1392113b24dd3815e98dece15493cc3dfd8fcea6%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create a copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new"

**Comment by TT9gth** [comment]
Hi,

I'm looking forward to use this App_Perf tool for the monitoring, when I tried implementing on Windows, I faced below given errors.
I set up all the required Prerequisites in my system, in ruby I'm not able to run below-given command.

./bin/setup

So I tried installing each individually (system "yarn install" & system "gem install bundler).

The next step is to run the below command.
bundle exec foreman start
I'm getting below error after executing the above command.
"https://github.com/productboard/postgres_ext.git (at rails-6@42d908a) is not yet checked out. Run bundle install first."

and when I'm trying to run "bundle install" command, again getting the below error.

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Error: "First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22https+%2F%2Fgithub.com%2Fproductboard%2Fpostgres_ext.git%22+%22C+%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fcache%2Fbundler%2Fgit%2Fpostgres_ext-1392113b24dd3815e98dece15493cc3dfd8fcea6%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create a copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new"
