### ISSUE TITLE
Suggested Features to work on - WIP

### ISSUE THREAD

**Issue by blasterpal** [randy-girard/app_perf#6]
Randy, just putting some ideas down here as I've explored the app. Getting traction on a project like this would be great, having a nice open source option to New Relic when you can't afford or can't send your data to cloud like my company makes this project attractive. I'd be happy to help. You can find my email if you'd prefer to discuss offline.

I'm using this issue to jot down ideas as come across them. I suggest we can discuss here and then break them into individual issues as you agree on their merit.

## Less hard - A

- [ ] Create app signup for admin (normal devise workflow). (requires basic SMTP setup)
 * after confirmation, the user can then add agent
- [x] Create basic admin CRUD to add users.
- [ ] To keep simple at first have just roles: `:admin`, `:reader`. Admin can add other users to App and make alerts,etc (see below)
- [ ] Need a means to filter many different URLs from tracing (heartbeat urls,etc)
- [x] Test agent on multiple Rubies using https://github.com/thoughtbot/appraisal (seems this is most important for stability and traction of app). Also picking which rubies you don't want to support now is important IMO. I personally feel the agent should be heavily tested and the most critical component to not affect an app using it.
- [x] Dockerize the app and put on registry (I've already started this for my own purposes), IMO this can help with traction. Make it dead easy for folks to kick the tires in a few minutes.
- [ ] Create Test Heroku environment for Devs to pushes changes and try out (separate from main app).
- [ ] ChatOps support, Slack, HipChat for alerts and also possibly create a process to monitor certain rooms and have limited ChatOps commands like: 
`app_env alerts recent`, `app_env metrics prod_app`.

## Harder - B
- [ ] Create a means to set error thresholds for variety of telemetry (slow queries, exceptions)
- [ ] Add alerting (SMS) for when #1 conditions occur.
- [ ] Custom regex filter for SQL sanitization (this is more personal for my use case as I have financial data in my applications, i.e. bank account numbers). 

## Long Term - C (pie in the sky)
- [x] Switch to purely Rails API for AppPerf and create simple UI based on React Native?, Vue,etc and a mobile,responsive. 
- [ ] Above allows folks to create their own UIs, mobile apps,etc.

**Comment by randy-girard** [comment]
I think this is a great start! I'm glad to have some other interest in this as well, will really help move it along I think.

The user mgmt and alerting systems were both things that I had in mind but haven't gotten to implementing yet.

**Comment by blasterpal** [comment]
## Other Ideas:

1. Add host basic info, cpu, ram, name and add to POST data in Gem for use.

**Comment by randy-girard** [comment]
There is some host data that gets sent now, check in the monitors. And host name is alway ssent.

**Comment by blasterpal** [comment]
@randy-girard ok thanks, I wasn't sure.

**Comment by randy-girard** [comment]
I just added a user management for apps where you can add existing (or invite new) users to an app. Also, you can create an app ahead of time and then use the app license key to push to it, or just use your user license key with an app name and push it automatically. Not sure I want to open the app up to allowing anyone to sign up. It should be on the administrator to add their users (unless i release a public version, which I would have to charge for in some capacity.

**Comment by randy-girard** [comment]
Docker compose has been added.

**Comment by MACscr** [comment]
php agent! =)

**Comment by randy-girard** [comment]
Added to dockerhub. https://hub.docker.com/r/rgirard59/app-perf/

**Comment by randy-girard** [comment]
Gem is using appraisal gem now and tested on multiple rubies.

**Comment by randy-girard** [comment]
I am using Roda for an API now. Currently it supports the overview and database views pages. I will continue to add more and eventually document it.

**Comment by randy-girard** [comment]
Closing in favor of projects
